AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'test/test_helper.rb'
    - 'vendor/**/*'
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
